import Foundation
import CoreData

@objc(AnimeItem)
public class AnimeItem: NSManagedObject {
    // You usually won't need to add custom code here
    // This file will be generated by Xcode when you create NSManagedObject subclasses
}
